world_address = "0x077d7feaa1055402978560511368f9c22805a360633e8a359483868960cf1e00"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[events]
raw = true

[indexing]
namespaces = ["bm_0_1_9"]
pending = true
world_block = 2210150
contracts = [
]

# Performance tuning
events_chunk_size = 1024
blocks_chunk_size = 10240
polling_interval = 500
max_concurrent_tasks = 100
